management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring:
  profile: peer1
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8070
eureka:
  instance:
    hostname: eureka-peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer1:8070/eureka/

---
spring:
  profile: peer2
  application:
    name: eureka-server
server:
  port: 8072
eureka:
  instance:
    hostname: eureka-peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer2:8072/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5

---
spring:
  profile: peer3
  application:
    name: eureka-server
server:
  port: 8073
eureka:
  instance:
    hostname: eureka-peer3
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-peer3:8073/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5



