spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8070
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8071/eureka/, http://peer2:8072/eureka

---
spring:
  profile: peer1
  application:
    name: eureka-server
server:
  port: 8071
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/, http://peer2:8072/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5

---
spring:
  profile: peer2
  application:
    name: eureka-server
server:
  port: 8072
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/, http://peer1:8071/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5

---

management:
  endpoints:
    web:
      exposure:
        include: "*"


